department_app/views/__init__.py
"""
__init__.py file of views module with
imported auth, employee_view and department_view submodules
Register the user blueprint and specify the logic on '/' and '/home' addresses
"""

# pylint: disable=cyclic-import
from flask import Blueprint
from flask import render_template

user = Blueprint('user', __name__)

# pylint: disable=import-self
# pylint: disable=wrong-import-position
# because the blueprint must be registered before importing the views
from . import auth
from . import employee_view
from . import department_view


@user.route('/')
@user.route('/home')
def home_page():
    """
    Render the home page template on the / route
    """
    return render_template('home.html')

department_app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <!-- Site Icon -->
    <link rel="icon" href="data:;base64,=">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <!-- Navbar here -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('user.home_page') }}">Department App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation bar tabs -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.home_page') }}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            </ul>
            {% if current_user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.show_departments') }}">Departments</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.show_employees') }}">Employees</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link">Welcome, {{ current_user.username }}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.logout_page') }}">Logout</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.login_page') }}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('user.register_page') }}">Register</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        <button type="button" class="m1-2 mb-1 close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
</body>
</html>

department_app/templates/home.html
{% extends 'base.html' %}
{% block title %}
Welcome
{% endblock %}
{% block content %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-dark" style="color:white">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Department App</h1>
        {% if current_user.is_authenticated %}
            <p class="lead font-weight-normal">Move to the Departments by clicking the link below</p>
            <a class="btn btn-primary" href="{{ url_for('user.show_departments') }}">View Departments</a>
        {% else %}
            <p class="lead font-weight-normal">Start using app by clicking the link below</p>
            <a class="btn btn-primary" href="{{ url_for('user.login_page') }}">Get Started</a>
        {% endif %}
    </div>
</div>
{% endblock %}